{% set version = "3.3.0" %}

package:
  name: threadpoolctl
  version: {{ version }}

source:
  url: https://github.com/joblib/threadpoolctl/archive/{{ version }}.tar.gz
  sha256: 8ba449778acf0be86d2d87c0a4caee35c4c360afb8d7cbd994321c7cab11ac88

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m flit install

requirements:
  host:
    - python >=3.8
    - flit
  run:
    - python >=3.8

test:
  requires:
    - numpy
  imports:
    - threadpoolctl
  commands:
    - python -m threadpoolctl -i numpy

about:
  home: https://github.com/joblib/threadpoolctl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python helpers to control the threadpools of native libraries

  description: |
    Python helpers to introspect and limit the number of threads used
    in native libraries that handle their own internal threadpool
    (BLAS and OpenMP implementations).
  doc_url: https://github.com/joblib/threadpoolctl
  dev_url: https://github.com/joblib/threadpoolctl

extra:
  recipe-maintainers:
    - ogrisel
    - tomMoral
    - jeremiedbb
