{% set version = "3.5.0" %}

package:
  name: threadpoolctl
  version: {{ version }}

source:
  url: https://github.com/joblib/threadpoolctl/archive/{{ version }}.tar.gz
  sha256: 3d941a397b35d15522d095173d06adeadc1d95f81f63b35e078e77b2d7c80401

build:
  skip: true  # [py<38]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core >2,<4
  run:
    - python
  run_constrained:
    - blas=*=openblas  # [osx and x86_64]

test:
  source_files: tests
  requires:
    - pip
    - numpy
    - pytest
  imports:
    - threadpoolctl
  commands:
    - pip check
    - python -m threadpoolctl -i numpy
    - pytest -v tests  # [not (aarch64 or s390x)]
    # linux-aarch64 (neoversen1) and s390x (z14) are unrecognized
    # architectures on Prefect.  linux-aarch64 (m1) is perfectly OK.
    - pytest -v tests -k 'not test_architecture'  # [aarch64 or s390x]

about:
  home: https://github.com/joblib/threadpoolctl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python helpers to control the threadpools of native libraries
  description: |
    Python helpers to introspect and limit the number of threads used
    in native libraries that handle their own internal threadpool
    (BLAS and OpenMP implementations).
  doc_url: https://github.com/joblib/threadpoolctl
  dev_url: https://github.com/joblib/threadpoolctl

extra:
  recipe-maintainers:
    - ogrisel
    - tomMoral
    - jeremiedbb
